version: '3'
services:
  db: 
    image: mongo:3.4
  backend:
    image: python:3.6.8
    volumes: 
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && pip3 install -r requirements.txt && python app.py"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80